from PyQt5 import QtCore, QtGui, QtWidgets


class Gui(object):

    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(819, 668)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 20, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(43)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(120, 120, 581, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.wakeup = QtWidgets.QPushButton(self.tab)
        self.wakeup.setGeometry(QtCore.QRect(170, 100, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.wakeup.setFont(font)
        self.wakeup.setObjectName("wakeup")
        self.sendconfig = QtWidgets.QPushButton(self.tab)
        self.sendconfig.setGeometry(QtCore.QRect(170, 190, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sendconfig.setFont(font)
        self.sendconfig.setObjectName("sendconfig")
        self.getftp = QtWidgets.QPushButton(self.tab)
        self.getftp.setGeometry(QtCore.QRect(170, 280, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.getftp.setFont(font)
        self.getftp.setObjectName("getftp")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 130, 311, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.keylogger = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.keylogger.setChecked(True)
        self.keylogger.setObjectName("keylogger")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.keylogger)
        self.tracker = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.tracker.setChecked(True)
        self.tracker.setObjectName("tracker")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tracker)
        self.samplingFrequencyLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.samplingFrequencyLabel.setObjectName("samplingFrequencyLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.samplingFrequencyLabel)
        self.trackfreq = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.trackfreq.setObjectName("trackfreq")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trackfreq)
        self.screenshotFrequencyLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.screenshotFrequencyLabel.setObjectName("screenshotFrequencyLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.screenshotFrequencyLabel)
        self.screenshotfreq = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.screenshotfreq.setObjectName("screenshotfreq")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.screenshotfreq)
        self.screenshotTriggerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.screenshotTriggerLabel.setObjectName("screenshotTriggerLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.screenshotTriggerLabel)
        self.triggers = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.triggers.setObjectName("triggers")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.triggers)
        self.debugmode = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.debugmode.setChecked(True)
        self.debugmode.setObjectName("debugmode")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.debugmode)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 541, 201))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.samplingFrequencyLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.samplingFrequencyLabel_2.setObjectName("samplingFrequencyLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.samplingFrequencyLabel_2)
        self.baseurl = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.baseurl.setObjectName("baseurl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baseurl)
        self.screenshotFrequencyLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.screenshotFrequencyLabel_2.setObjectName("screenshotFrequencyLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.screenshotFrequencyLabel_2)
        self.ftpurl = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ftpurl.setObjectName("ftpurl")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ftpurl)
        self.screenshotTriggerLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.screenshotTriggerLabel_2.setObjectName("screenshotTriggerLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.screenshotTriggerLabel_2)
        self.ftpuser = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ftpuser.setObjectName("ftpuser")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ftpuser)
        self.fTPPassLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fTPPassLabel.setObjectName("fTPPassLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.fTPPassLabel)
        self.ftppass = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ftppass.setObjectName("ftppass")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ftppass)
        self.fCommLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fCommLabel.setObjectName("fCommLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.fCommLabel)
        self.commfreq = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.commfreq.setObjectName("commfreq")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.commfreq)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(170, 60, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(230, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 541, 81))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.samplingFrequencyLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.samplingFrequencyLabel_3.setObjectName("samplingFrequencyLabel_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.samplingFrequencyLabel_3)
        self.shellcommand = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.shellcommand.setText("")
        self.shellcommand.setObjectName("shellcommand")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shellcommand)
        self.screenshotFrequencyLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.screenshotFrequencyLabel_3.setObjectName("screenshotFrequencyLabel_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.screenshotFrequencyLabel_3)
        self.filepath = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.filepath.setText("")
        self.filepath.setObjectName("filepath")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filepath)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Malware Control Panel"))
        self.wakeup.setText(_translate("Dialog", "Ellácska, wake up!!!"))
        self.sendconfig.setText(_translate("Dialog", "Send config data!!!"))
        self.getftp.setText(_translate("Dialog", "Get stolen data!!!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Attack"))
        self.keylogger.setText(_translate("Dialog", "Keylogging"))
        self.tracker.setText(_translate("Dialog", "Window Tracking"))
        self.samplingFrequencyLabel.setText(_translate("Dialog", "Sampling Frequency"))
        self.trackfreq.setText(_translate("Dialog", "0.1"))
        self.screenshotFrequencyLabel.setText(_translate("Dialog", "Screenshot Frequency"))
        self.screenshotfreq.setText(_translate("Dialog", "50"))
        self.screenshotTriggerLabel.setText(_translate("Dialog", "Screenshot Triggers"))
        self.triggers.setText(_translate("Dialog", "facebook"))
        self.debugmode.setText(_translate("Dialog", "Debug"))
        self.label_2.setText(_translate("Dialog", "Window tracking & Keylogging"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Logging"))
        self.samplingFrequencyLabel_2.setText(_translate("Dialog", "Base URL"))
        self.baseurl.setText(_translate("Dialog", "http://facebook-user-profile.herokuapp.com/malware"))
        self.screenshotFrequencyLabel_2.setText(_translate("Dialog", "FTP:"))
        self.ftpurl.setText(_translate("Dialog", "ftp.atw.hu"))
        self.screenshotTriggerLabel_2.setText(_translate("Dialog", "FTP user"))
        self.ftpuser.setText(_translate("Dialog", "kiserletimuto"))
        self.fTPPassLabel.setText(_translate("Dialog", "FTP pass"))
        self.ftppass.setText(_translate("Dialog", "patti"))
        self.fCommLabel.setText(_translate("Dialog", "Comm freq"))
        self.commfreq.setText(_translate("Dialog", "900"))
        self.label_3.setText(_translate("Dialog", "Server Communication"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Communication"))
        self.label_4.setText(_translate("Dialog", "Backdoor "))
        self.samplingFrequencyLabel_3.setText(_translate("Dialog", "Shell command"))
        self.screenshotFrequencyLabel_3.setText(_translate("Dialog", "File Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Backdoor"))


